site_name: EAVE-II Data Dictionary
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    scheme: eave
  custom_dir: overrides
  icon:
    admonition:
      note: fontawesome/solid/table
      
plugins:
  - search
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - mknotebooks:
      enable_default_jupyter_cell_styling: true
      write_markdown: false
      binder: false

  
markdown_extensions:
  - tables
  #- include
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
  
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Overview: index.md
  - Datasets:
      - Demographics: demographics.md
      - QCOVID: qcovid.md
      - Serology: serology.md
      - Severe Outcomes:
          - Cases: severe-cases.md
          - Hospitalisations: hospitalisations.md
          - Deaths: deaths.md
      - Testing:
          - PCR Tests: testing.md
          - Genomic Sequencing: sequencing.md
      - Vaccines: vaccines.md
      - Other:
          - Test
  - EAVE Helpers: EAVE Helpers.ipynb
